services:
  # ===============================
  # 🌐 CLIENT (Frontend)
  # ===============================
  - type: web
    name: smarttalk-client
    env: node
    plan: free
    region: oregon
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://smarttalk-server.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false

  # ===============================
  # ⚙️ SERVER (Backend)
  # ===============================
  - type: web
    name: smarttalk-server
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000

      # 🌍 App Config
      - key: FRONTEND_URL
        value: https://smarttalk-client.onrender.com
      - key: VITE_API_URL
        value: https://smarttalk-server.onrender.com

      # 💾 MongoDB
      - key: MONGODB_URI
        sync: false

      # 🔥 Firebase Admin SDK
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

      # 💰 Billing
      - key: CALL_RATE_PER_SECOND
        value: "0.0033"
      - key: MIN_START_BALANCE
        value: "0.5"
      - key: DEFAULT_CURRENCY
        value: "USD"
      - key: NEW_USER_BONUS
        value: "5"
      - key: BONUS_EXPIRY_DAYS
        value: "90"

      # 💳 Payment Integrations
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYSTACK_SECRET
        sync: false
      - key: FLW_SECRET
        sync: false