services:
  - type: web
    name: chat-wallet-call
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18

      # Firebase (from .env)
      - fromGroup: firebase

      # App Config (from .env)
      - fromGroup: app