name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d20mrfp5pdvs73976a00?key=${{ secrets.RENDER_API_KEY }}"