name: CI & Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # set your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # change to your test script

      - name: Build project
        run: npm run build  # change to your build script

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null -X POST "https://api.render.com/deploy/srv-d20mrfp5pdvs73976a00" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json")
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Deployment failed with status code $RESPONSE"
            exit 1
          else
            echo "Deployment triggered successfully"
          fi