name: CI & Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies (from root where server.js is)
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests defined"

      # 5️⃣ Trigger Render Deployment
      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering Render deploy..."
          RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null -X POST \
            "https://api.render.com/deploy/srv-d3cfik7diees73fvfdng" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json")
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "❌ Deployment failed with status code $RESPONSE"
            exit 1
          else
            echo "✅ Deployment triggered successfully"
          fi